stages:
  - build
  - deploy

default:
  tags:
    - Builder

build_backend:
  stage: build
  only:
    - main
  before_script:
    - echo $CI_REGISTRY
    - docker logout $CI_REGISTRY
    - echo "$CI_REGISTRY_IMAGE;   $CI_COMMIT_REF_NAME;   $CI_COMMIT_SHORT_SHA"
  script:
    - echo $CI_REGISTRY_USER    $CI_REGISTRY
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE $CI_COMMIT_SHORT_SHA
    - docker build -t $CI_REGISTRY_IMAGE --pull --force-rm .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push -a $CI_REGISTRY_IMAGE
  retry: 1

deploy_to_server:
  stage: deploy
  script:
    - ansible-playbook -i deploy/hosts.yml deploy/deploy.yml -e pass=$CI_REGISTRY_PASSWORD -e login=$CI_REGISTRY_USER -e ci_registry=$CI_REGISTRY -v