version: '3'

services:
  backend:
    restart: always
    image: 192.168.0.105:5005/django-projects/devops_abc:latest
    container_name: backend
    volumes:
      - /tmp/static:/app/static
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - db

  db:
    restart: always
    image: postgis/postgis:13-3.3-alpine
    container_name: database
    volumes:
      - /tmp/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
