# pull official base image
FROM python:3.10.7-alpine3.15 as dependencies
# set work directory
WORKDIR /app
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# install dependencies
RUN pip install --upgrade --no-cache pip
RUN apk update --no-cache \
    && apk add gcc git g++ musl-dev make python3-dev libffi-dev postgresql-dev postgresql-client openldap-dev gettext cairo-dev
RUN pip install --upgrade pip poetry
COPY ./pyproject.toml .
RUN poetry config virtualenvs.create false
RUN poetry install
RUN poetry add gunicorn

# PROD images
FROM dependencies AS base
ADD . /app
RUN chmod +x entrypoint.sh
CMD ["./entrypoint.sh"]
